version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: colloq_postgres
    environment:
      POSTGRES_USER: colloq_user
      POSTGRES_PASSWORD: colloq_password
      POSTGRES_DB: colloq_dev
      # Uruchomi init-dbs.sql, aby utworzyć tę bazę dla pytest
      POSTGRES_MULTIPLE_DATABASES: "colloq_test" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    ports:
      - "5432:5432"
    networks:
      - colloq_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U colloq_user -d colloq_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: colloq_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@colloq.pl
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - colloq_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  colloq_network:
    driver: bridge
