from sqlalchemy import Column, Integer, String, Text, Float, DateTime, Boolean, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from .database import Base


class University(Base):
    """
    Database model for universities.
    Root of the data hierarchy.
    """
    __tablename__ = "universities"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, index=True, nullable=False)
    name_en = Column(String, nullable=True)  # English name
    name_pl = Column(String, nullable=True)  # Polish name
    city = Column(String, nullable=True)
    region = Column(String, nullable=True)
    type = Column(String, nullable=True)  # e.g., "Publiczna", "Prywatna"
    image_url = Column(String, nullable=True)
    is_approved = Column(Boolean, default=False)

    # Relationships
    users = relationship("User", back_populates="university")
    fields_of_study = relationship("FieldOfStudy", back_populates="university")
    notes = relationship("Note", back_populates="university")


class FieldOfStudy(Base):
    """
    Database model for Fields of Study (Kierunki studiów).
    Hierarchy Level 2: University -> FieldOfStudy
    """
    __tablename__ = "fields_of_study"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)  # e.g., "Informatyka", "Psychologia"
    degree_level = Column(String, nullable=True)  # e.g., "I stopnia", "Magisterskie"
    is_approved = Column(Boolean, default=False)

    # Foreign Keys
    university_id = Column(Integer, ForeignKey("universities.id"), nullable=False)

    # Relationships
    university = relationship("University", back_populates="fields_of_study")
    subjects = relationship("Subject", back_populates="field_of_study")


class Subject(Base):
    """
    Database model for Subjects (Przedmioty).
    Hierarchy Level 3: FieldOfStudy -> Subject
    """
    __tablename__ = "subjects"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)  # e.g., "Analiza Matematyczna 1"
    semester = Column(Integer, nullable=True)  # e.g., 1, 2, 3...
    is_approved = Column(Boolean, default=False)

    # Foreign Keys
    field_of_study_id = Column(Integer, ForeignKey("fields_of_study.id"), nullable=False)

    # Relationships
    field_of_study = relationship("FieldOfStudy", back_populates="subjects")
    notes = relationship("Note", back_populates="subject")


class User(Base):
    """
    Database model for users.
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    nickname = Column(String, nullable=True)

    # Flags
    is_verified = Column(Boolean, default=False)
    is_admin = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True)

    # Foreign key
    university_id = Column(Integer, ForeignKey("universities.id"), nullable=False)

    # Relationships
    university = relationship("University", back_populates="users")
    notes = relationship("Note", back_populates="author")


class Note(Base):
    """
    Database model for student notes.
    The core content entity.
    """
    __tablename__ = "notes"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=True)
    content = Column(Text, nullable=True)

    # Multimedia & Links
    image_url = Column(String, nullable=True)
    video_url = Column(String, nullable=True)  # YouTube/Vimeo link
    link_url = Column(String, nullable=True)  # External resource link

    # AI & Metadata
    tags = Column(String, nullable=True)  # Comma-separated tags generated by AI
    score = Column(Float, default=0.0)
    is_approved = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Foreign keys
    author_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    university_id = Column(Integer, ForeignKey("universities.id"), nullable=False)
    subject_id = Column(Integer, ForeignKey("subjects.id"), nullable=True)

    # Relationships
    author = relationship("User", back_populates="notes")
    university = relationship("University", back_populates="notes")
    subject = relationship("Subject", back_populates="notes")

    # AI generated content relation
    flashcards = relationship("Flashcard", back_populates="note", cascade="all, delete-orphan")


class Flashcard(Base):
    """
    Database model for AI-generated Flashcards.
    """
    __tablename__ = "flashcards"

    id = Column(Integer, primary_key=True, index=True)
    question = Column(Text, nullable=False)
    answer = Column(Text, nullable=False)

    # Foreign key
    note_id = Column(Integer, ForeignKey("notes.id"), nullable=False)

    # Relationship
    note = relationship("Note", back_populates="flashcards")